import Navbar from "@/components/navbar/Navbar";
import { Toaster } from "react-hot-toast";
import getCurrentUser from "@/actions/getCurrentUser";

export const metadata = {
  title: "Weavement",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <main lang="en">
      <Navbar currentUser={currentUser} />
      {children}
    </main>
  );
}
