import DeletePortfolioConfirm from "@/components/confirms/DeletePortfolioConfirm";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div lang="en">
      <DeletePortfolioConfirm />
      <div>{children}</div>
    </div>
  );
}
